# Generated by Django 3.1 on 2020-09-02 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias',
            new_name='Empresa',
        ),
    ]
