# Generated by Django 3.1 on 2020-09-02 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20200901_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresa',
            new_name='ResenaEmpresa',
        ),
    ]
