# Generated by Django 3.1 on 2020-09-02 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20200901_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResenaEmpresa',
            new_name='EmpresaNota',
        ),
    ]
