# Generated by Django 3.1 on 2020-09-02 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20200901_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpresaNota',
            new_name='Nota',
        ),
    ]
