# Generated by Django 3.0.8 on 2020-08-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(blank=True, db_index=True, help_text='Unique identifier for transit agency', max_length=255)),
                ('name', models.CharField(help_text='Full name of the transit agency', max_length=255)),
                ('url', models.URLField(blank=True, help_text='URL of the transit agency')),
                ('timezone', models.CharField(help_text='Timezone of the agency', max_length=255)),
                ('lang', models.CharField(blank=True, help_text='ISO 639-1 code for the primary language', max_length=2)),
                ('phone', models.CharField(blank=True, help_text='Voice telephone number', max_length=255)),
                ('fare_url', models.URLField(blank=True, help_text='URL for purchasing tickets online')),
                ('email', models.EmailField(blank=True, help_text='Customer Service email', max_length=254)),
            ],
        ),
    ]
