# Generated by Django 3.0.8 on 2020-08-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='identificador',
            field=models.CharField(default='hola', max_length=32),
            preserve_default=False,
        ),
    ]
