# Generated by Django 3.0.8 on 2020-08-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0002_comunidad_identificador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunidad',
            old_name='identificador',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='resena',
            field=models.TextField(verbose_name='Reseña de la comunidad'),
        ),
    ]
