# Generated by Django 3.0.8 on 2020-08-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0003_auto_20200818_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='codigo_postal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='poblacion',
            field=models.IntegerField(default=0),
        ),
    ]
