# Generated by Django 3.0.8 on 2020-08-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0004_auto_20200819_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='area',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='codigo_postal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='poblacion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
